// <auto-generated />
using GIT_MVC_GROUP6B.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GIT_MVC_GROUP6B.Migrations
{
    [DbContext(typeof(GIT_MVC_GROUP6BContext))]
    partial class GIT_MVC_GROUP6BContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GIT_MVC_GROUP6B.Models.Entities.Thing1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Thing1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            Age = 3,
                            Name = "C"
                        },
                        new
                        {
                            Id = 4,
                            Age = 4,
                            Name = "D"
                        },
                        new
                        {
                            Id = 5,
                            Age = 5,
                            Name = "E"
                        },
                        new
                        {
                            Id = 6,
                            Age = 6,
                            Name = "F"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
